---
title: Service
title-block-banner: "#4499CF"
toc: false
engine: knitr
freeze: false
---

```{css, echo=FALSE}
#title-block-header .description {
    display: none;
}
```

I’ve taken on a few service projects/roles in recent years, in addition to the usual professional service like referee reports, conference organization, etc. Brief descriptions, and links to other information if available, are below:

# Department Service

- First Year Graduate Student Mentor, 2021-2025
- [Professionalism Workshop](https://phdworkshop.classes.ianmccarthyecon.com/). This is a workshop for 2nd-5th year Economics PhD students. We cover lots of “unwritten” things that most PhD students should know, including best practices for workflow, conferences, presentations, and ultimately the job market.
- Interim Director of Graduate Studies, 2024-2025

# External Mentorship

As a first-generation college student, I’m well aware of how challenging it can be to navigate into/around academia for those of use not already connected to that space. So I try to volunteer my time as a mentor as generously as possible. A few of my regular mentorship efforts are listed below:

- ASHEcon annual mentorship sessions, 2018-2025
- Research in Color, 2019-2020 and 2020-2021
- Association for Mentoring and Inclusion in Economics, 2022-2024

# Editorial Roles

- Associate Editor, Southern Economic Journal, 2025
- ASHEcon Program Chair, Physician Labor Markets and Treatment Decisions, 2024-2026
  
# Other Appointments

- Visiting Scholar, Congressional Budget Office, 2021-2023