---
title: "Owning the Agent: Hospital Influence on Physician Behaviors"
date: 2025-02-01
author:
  - name: Haizhen Lin
    url: https://host.kelley.iu.edu/hzlin/
    affiliation: Kelley School of Business, Indiana University
  - name: Ian McCarthy
    url: https://www.ianmccarthyecon.com/
    orcid: 0000-0001-7942-3468
    affiliation: Department of Economics, Emory University
  - name: Michael Richards
    url: https://michaelrichards.yourwebsitespace.com/
    affiliation: Brooks School of Public Policy, Cornell University
  - name: Christopher Whaley
    url: https://vivo.brown.edu/display/cmwhaley
    affiliation: School of Public Health, Brown University    
categories:
  - Hospitals
  - Physicians
  - Vertical integration
pub-info:
  reference: >-
    Haizhen Lin, <strong>Ian McCarthy</strong>, Michael Richards, and Christopher Whaley. 2025. “Owning the Agent: Hospital Influence on Physician Behaviors,” <em>Accepted</em> at <em>Journal of Human Resources</em>
  links:
  - name: Working Paper
    url: "https://www.nber.org/papers/w28859"
    icon: fa-solid fa-file-pdf
  - name: Code
    url: https://github.com/imccart/physician-hospital-VI
    icon: fa-brands fa-github
---

## Important links

- [NBER Working Paper](https://www.nber.org/papers/w28859)
- [GitHub repository](https://github.com/imccart/physician-hospital-VI)


## Abstract

The organizational structure of U.S. health care markets has changed dramatically in recent years, with nearly half of physicians now employed by hospitals. This trend toward increasing vertical alignment between physicians and hospitals may alter physician behavior relative to physicians remaining in independent or group practices. We examine the effects of such vertical alignment using an instrumental variable strategy and a clinical context facilitating well-defined episodes of care in order to capture effects of integration beyond a single hospital or physician visit. When physicians treat patients at hospitals in which they are integrated, we find increases in total episode spending of around 5\%, primarily driven by the administrative substitution of office visits with outpatient visits and associated site-of-care payment differentials. We also estimate a large and statistically significant reduction in overall service counts and claims within an episode, with some evidence of an increase in the intensity of services provided. Ultimately, acquiring hospitals capture more revenue following a physician practice acquisition; yet, the smaller overall bundle of care generates no net savings to Medicare due partly to higher intensity of services as well as site-based payment rules favorable to hospitals.
