---
title: "New Data Show Nongroup Plans Paid Significantly Lower Prices to Providers Than Employer Plans In 2021"
date: 2024-09-02
author:
  - name: Caroline Hanson
    url: https://www.linkedin.com/in/caroline-hanson-584b9622/
    affiliation: Congressional Budget Office
  - name: Ian McCarthy
    url: https://www.ianmccarthyecon.com/
    orcid: 0000-0001-7942-3468
    affiliation: Department of Economics, Emory University
  - name: Eamon Molloy
    url: https://www.linkedin.com/in/eamon-molloy-3131a744/
    affiliation: Congressional Budget Office
  - name: Karen Stockley
    url: https://www.linkedin.com/in/karen-stockley-51981021/
    affiliation: Medicare Payment Advisory Commission
categories:
  - Health care pricing
pub-info:
  reference: >-
    Caroline Hanson, <strong>Ian McCarthy</strong>, Eamon Molloy, and Karen Stockley. “New Data Show Nongroup Plans Paid Significantly Lower Prices to Providers Than Employer Plans In 2021,” <em>Revise and Resubmit</em> at <em>Health Affairs</em>
---



## Abstract

Numerous studies show that employer plans pay providers significantly more than Medicare, but less is known about prices in nongroup plans, where narrow networks and low-cost insurers are more prevalent. We estimate prices for three market segments—on-marketplace nongroup, off-marketplace nongroup, and small group—and for three types of services—inpatient hospital, outpatient hospital, and professional—relative to a Medicare benchmark. We use 2021 claims data covering virtually all enrollment in Affordable Care Act risk-adjusted plans. In aggregate, marketplace prices are 152% of Medicare prices, while the prices paid in small employer plans are 179% of Medicare. Comparing across market segments, relative to small group, marketplace professional prices are 6.9% lower, inpatient prices are 13.3% lower, and outpatient prices are 26.3% lower. Off-marketplace prices fall between marketplace and small group prices. The finding that nongroup prices are significantly lower than prices paid by employer plans – more so than indicated by prior research – is important for understanding federal subsidies and affordability for nongroup coverage and evaluating policies such as a nongroup public option with prices capped at a percentage of Medicare.